version: "3.1"

services:
  order-service:
    build: ./order-service
    depends_on:
      - queue
    ports:
      - 8000:80
    environment:
      QUEUE_HOST: queue:6379

  shipping-service:
    build: ./shipping-service
    depends_on:
      - queue
    environment:
      QUEUE_HOST: queue:6379
      TRUCK_AM_HOST: truc
      TRUCK_MG_HOST: truck-mg-service
      TRUCK_RS_HOST: truck-rs-service

  truck-am-service:
    build: ./truck-service
    depends_on:
      - database
    environment:
      DATABASE_CONNECTION: mongodb://admin:admin@database/?w=majority
      DATABASE_NAME: raptorslog
      DELIVERY_TIME: 1

  truck-mg-service:
    build: ./truck-service
    depends_on:
      - database
    environment:
      DATABASE_CONNECTION: mongodb://admin:admin@database/?w=majority
      DATABASE_NAME: raptorslog
      DELIVERY_TIME: 2
      
  truck-rs-service:
    build: ./truck-service
    depends_on:
      - database
    environment:
      DATABASE_CONNECTION: mongodb://admin:admin@database/?w=majority
      DATABASE_NAME: raptorslog
      DELIVERY_TIME: 3    

  queue:
    image: redis
    ports:
      - 6379:6379

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: raptorslog

  database-web-client:
    image: mongo-express
    depends_on:
      - database
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
