apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  type: NodePort
  ports:
    - port: 80
      name: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: order
spec:
  backend:
    serviceName: order
    servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-service
          image: augustopimenta/raptorslog-order-service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: web
          env:
            - name: QUEUE_HOST
              value: queue:6379
